### PR TITLE
SMTC-48: Split types out into separate files

### PR DESCRIPTION
**Pull request by tabgok**
Prior to this change we had a 700+ line file with all the different types in it.  After this change each of the different types is in its own file.

### CODE REVIEW

**Comment by fpddog** [comment]
We're going to have to convey several concepts (types, properties, aspects, ...) see: https://docs.google.com/document/d/1dSgEMsCAV6PnNwRT5SRUEvUJz4rSyNDZ7PkbuYPQvXw/edit#heading=h.n8i3ythp7cbb so I'm wondering if we could move the types into their own folder? Beyond that I think it's just iterating on these definitions, which we'll do in other PRs. 

Let me know if this makes sense.

**Comment by majorgreys** [comment]
I am not sure this is a good change. For instance, this looks to me like I am repeating myself:

```
from semantics.intake_resolved_http_span import IntakeResolvedHttpSpan
from semantics.intake_resolved_db_span import IntakeResolvedDbSpan
from semantics.intake_resolved_span import IntakeResolvedSpan
from semantics.agent_payload import AgentPayload
```

https://github.com/DataDog/schema/pull/46/files#diff-0804403265d8163059d18fd4de725191f8674f0fcac0357d24c63a5effaa9284R9-R12

If the problem is that a maintaining single Python, what's a second of module organization we can add?

**Comment by fpddog** [comment]
One thing that we'll need is to be able to easily list all of the types for use cases such as "show me all of the types that have this property set to X that I really care about", like for Trust & Safety if they want to know which types are sensitive. This might be easier if we have a single file with all of the individual types and an array listing out all of the type objects.

**Comment by tabgok** [comment]
> be easier if we have a single file with all of the individual types and an array listing out all of the type

Check out the proposal here: https://docs.google.com/document/d/1dSgEMsCAV6PnNwRT5SRUEvUJz4rSyNDZ7PkbuYPQvXw/edit

**Review by fpddog — APPROVED** [review]
lgtm

**Pull request merged**
